CREATE TABLE [dbo].[Records]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[ExpirationDate] DateTime NOT NULL,
	[CreationDate] DateTime NOT NULL,
	[CarRegistartionNumber] NVARCHAR(255) NOT NULL,
	[AdditionalInfo] NVARCHAR(MAX) NULL,
	[ClientId] UNIQUEIDENTIFIER NOT NULL,
	[RecordType] INT NOT NULL,
	[VehicleType] INT NOT NULL,
	CONSTRAINT FK_INREGISTRARI_CLIENTI FOREIGN KEY (ClientId) REFERENCES dbo.[Clients] (Id),
	CONSTRAINT FK_INREGISTRARI_RECORDTYPES FOREIGN KEY (RecordType) REFERENCES dbo.[RecordTypes] (Id),
	CONSTRAINT FK_INREGISTRARI_VEHICLETYPE FOREIGN KEY (VehicleType) REFERENCES dbo.[VehicleType] (Id)
)